// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://souaiphyjhfaojzsymje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdWFpcGh5amhmYW9qenN5bWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjY4MjYsImV4cCI6MjA2NTg0MjgyNn0.sBh5rgTnocI_cGEn7XovfWeGFuIZuMWJqIZJHg8LtLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);